# Generated by Django 4.1 on 2022-08-31 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('catNombre', models.CharField(max_length=50)),
                ('catFoto', models.FileField(upload_to='categoria/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proCodigo', models.IntegerField(unique=True)),
                ('proNombre', models.CharField(max_length=255)),
                ('proPrecio', models.IntegerField()),
                ('proFoto', models.FileField(upload_to='productos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proCateforia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appTienda.categoria')),
            ],
        ),
    ]
